### ISSUE TITLE
Plan for Durable Team time at All Hnads

### ISSUE THREAD

**Issue by ejregithub** [ejregithub/mozorgtesting#5]
- [ ] Plan from David for meetings in morning on 
   - [ ] Q3 KRs
   - [ ] Next steps for DS
   - [ ] Any meetings w. Dirs/Team Leads to iron out new [prioritization model for work requests](https://docs.google.com/presentation/d/1MnxtGiPuYZ1KxFY-KM-NQh7VFlaysJp7gB4rBkJyFXo/edit)
